//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnBreakWeb.WebServices {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cliente", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Cliente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RutClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RazonSocialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreContactoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MailContactoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        private int IdActividadEmpresaField;
        
        private int IdTipoEmpresaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string RutCliente {
            get {
                return this.RutClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.RutClienteField, value) != true)) {
                    this.RutClienteField = value;
                    this.RaisePropertyChanged("RutCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string RazonSocial {
            get {
                return this.RazonSocialField;
            }
            set {
                if ((object.ReferenceEquals(this.RazonSocialField, value) != true)) {
                    this.RazonSocialField = value;
                    this.RaisePropertyChanged("RazonSocial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string NombreContacto {
            get {
                return this.NombreContactoField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreContactoField, value) != true)) {
                    this.NombreContactoField = value;
                    this.RaisePropertyChanged("NombreContacto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string MailContacto {
            get {
                return this.MailContactoField;
            }
            set {
                if ((object.ReferenceEquals(this.MailContactoField, value) != true)) {
                    this.MailContactoField = value;
                    this.RaisePropertyChanged("MailContacto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int IdActividadEmpresa {
            get {
                return this.IdActividadEmpresaField;
            }
            set {
                if ((this.IdActividadEmpresaField.Equals(value) != true)) {
                    this.IdActividadEmpresaField = value;
                    this.RaisePropertyChanged("IdActividadEmpresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int IdTipoEmpresa {
            get {
                return this.IdTipoEmpresaField;
            }
            set {
                if ((this.IdTipoEmpresaField.Equals(value) != true)) {
                    this.IdTipoEmpresaField = value;
                    this.RaisePropertyChanged("IdTipoEmpresa");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ActividadEmpresa", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ActividadEmpresa : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoEmpresa", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class TipoEmpresa : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebServices.OBServiciosSoap")]
    public interface OBServiciosSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento HelloWorldResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        OnBreakWeb.WebServices.HelloWorldResponse HelloWorld(OnBreakWeb.WebServices.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<OnBreakWeb.WebServices.HelloWorldResponse> HelloWorldAsync(OnBreakWeb.WebServices.HelloWorldRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ReadAllClientesResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReadAllClientes", ReplyAction="*")]
        OnBreakWeb.WebServices.ReadAllClientesResponse ReadAllClientes(OnBreakWeb.WebServices.ReadAllClientesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReadAllClientes", ReplyAction="*")]
        System.Threading.Tasks.Task<OnBreakWeb.WebServices.ReadAllClientesResponse> ReadAllClientesAsync(OnBreakWeb.WebServices.ReadAllClientesRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento rutCliente del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReadCliente", ReplyAction="*")]
        OnBreakWeb.WebServices.ReadClienteResponse ReadCliente(OnBreakWeb.WebServices.ReadClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReadCliente", ReplyAction="*")]
        System.Threading.Tasks.Task<OnBreakWeb.WebServices.ReadClienteResponse> ReadClienteAsync(OnBreakWeb.WebServices.ReadClienteRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento cliente del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateCliente", ReplyAction="*")]
        OnBreakWeb.WebServices.UpdateClienteResponse UpdateCliente(OnBreakWeb.WebServices.UpdateClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateCliente", ReplyAction="*")]
        System.Threading.Tasks.Task<OnBreakWeb.WebServices.UpdateClienteResponse> UpdateClienteAsync(OnBreakWeb.WebServices.UpdateClienteRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento rutCliente del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteCliente", ReplyAction="*")]
        OnBreakWeb.WebServices.DeleteClienteResponse DeleteCliente(OnBreakWeb.WebServices.DeleteClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteCliente", ReplyAction="*")]
        System.Threading.Tasks.Task<OnBreakWeb.WebServices.DeleteClienteResponse> DeleteClienteAsync(OnBreakWeb.WebServices.DeleteClienteRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ReadAllActResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReadAllAct", ReplyAction="*")]
        OnBreakWeb.WebServices.ReadAllActResponse ReadAllAct(OnBreakWeb.WebServices.ReadAllActRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReadAllAct", ReplyAction="*")]
        System.Threading.Tasks.Task<OnBreakWeb.WebServices.ReadAllActResponse> ReadAllActAsync(OnBreakWeb.WebServices.ReadAllActRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ReadAllTipoResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReadAllTipo", ReplyAction="*")]
        OnBreakWeb.WebServices.ReadAllTipoResponse ReadAllTipo(OnBreakWeb.WebServices.ReadAllTipoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReadAllTipo", ReplyAction="*")]
        System.Threading.Tasks.Task<OnBreakWeb.WebServices.ReadAllTipoResponse> ReadAllTipoAsync(OnBreakWeb.WebServices.ReadAllTipoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public OnBreakWeb.WebServices.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(OnBreakWeb.WebServices.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public OnBreakWeb.WebServices.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(OnBreakWeb.WebServices.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReadAllClientesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadAllClientes", Namespace="http://tempuri.org/", Order=0)]
        public OnBreakWeb.WebServices.ReadAllClientesRequestBody Body;
        
        public ReadAllClientesRequest() {
        }
        
        public ReadAllClientesRequest(OnBreakWeb.WebServices.ReadAllClientesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ReadAllClientesRequestBody {
        
        public ReadAllClientesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReadAllClientesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadAllClientesResponse", Namespace="http://tempuri.org/", Order=0)]
        public OnBreakWeb.WebServices.ReadAllClientesResponseBody Body;
        
        public ReadAllClientesResponse() {
        }
        
        public ReadAllClientesResponse(OnBreakWeb.WebServices.ReadAllClientesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReadAllClientesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public OnBreakWeb.WebServices.Cliente[] ReadAllClientesResult;
        
        public ReadAllClientesResponseBody() {
        }
        
        public ReadAllClientesResponseBody(OnBreakWeb.WebServices.Cliente[] ReadAllClientesResult) {
            this.ReadAllClientesResult = ReadAllClientesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReadClienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadCliente", Namespace="http://tempuri.org/", Order=0)]
        public OnBreakWeb.WebServices.ReadClienteRequestBody Body;
        
        public ReadClienteRequest() {
        }
        
        public ReadClienteRequest(OnBreakWeb.WebServices.ReadClienteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReadClienteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string rutCliente;
        
        public ReadClienteRequestBody() {
        }
        
        public ReadClienteRequestBody(string rutCliente) {
            this.rutCliente = rutCliente;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReadClienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadClienteResponse", Namespace="http://tempuri.org/", Order=0)]
        public OnBreakWeb.WebServices.ReadClienteResponseBody Body;
        
        public ReadClienteResponse() {
        }
        
        public ReadClienteResponse(OnBreakWeb.WebServices.ReadClienteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReadClienteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public OnBreakWeb.WebServices.Cliente ReadClienteResult;
        
        public ReadClienteResponseBody() {
        }
        
        public ReadClienteResponseBody(OnBreakWeb.WebServices.Cliente ReadClienteResult) {
            this.ReadClienteResult = ReadClienteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateClienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateCliente", Namespace="http://tempuri.org/", Order=0)]
        public OnBreakWeb.WebServices.UpdateClienteRequestBody Body;
        
        public UpdateClienteRequest() {
        }
        
        public UpdateClienteRequest(OnBreakWeb.WebServices.UpdateClienteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateClienteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public OnBreakWeb.WebServices.Cliente cliente;
        
        public UpdateClienteRequestBody() {
        }
        
        public UpdateClienteRequestBody(OnBreakWeb.WebServices.Cliente cliente) {
            this.cliente = cliente;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateClienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateClienteResponse", Namespace="http://tempuri.org/", Order=0)]
        public OnBreakWeb.WebServices.UpdateClienteResponseBody Body;
        
        public UpdateClienteResponse() {
        }
        
        public UpdateClienteResponse(OnBreakWeb.WebServices.UpdateClienteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateClienteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UpdateClienteResult;
        
        public UpdateClienteResponseBody() {
        }
        
        public UpdateClienteResponseBody(bool UpdateClienteResult) {
            this.UpdateClienteResult = UpdateClienteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteClienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteCliente", Namespace="http://tempuri.org/", Order=0)]
        public OnBreakWeb.WebServices.DeleteClienteRequestBody Body;
        
        public DeleteClienteRequest() {
        }
        
        public DeleteClienteRequest(OnBreakWeb.WebServices.DeleteClienteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteClienteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string rutCliente;
        
        public DeleteClienteRequestBody() {
        }
        
        public DeleteClienteRequestBody(string rutCliente) {
            this.rutCliente = rutCliente;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteClienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteClienteResponse", Namespace="http://tempuri.org/", Order=0)]
        public OnBreakWeb.WebServices.DeleteClienteResponseBody Body;
        
        public DeleteClienteResponse() {
        }
        
        public DeleteClienteResponse(OnBreakWeb.WebServices.DeleteClienteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteClienteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool DeleteClienteResult;
        
        public DeleteClienteResponseBody() {
        }
        
        public DeleteClienteResponseBody(bool DeleteClienteResult) {
            this.DeleteClienteResult = DeleteClienteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReadAllActRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadAllAct", Namespace="http://tempuri.org/", Order=0)]
        public OnBreakWeb.WebServices.ReadAllActRequestBody Body;
        
        public ReadAllActRequest() {
        }
        
        public ReadAllActRequest(OnBreakWeb.WebServices.ReadAllActRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ReadAllActRequestBody {
        
        public ReadAllActRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReadAllActResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadAllActResponse", Namespace="http://tempuri.org/", Order=0)]
        public OnBreakWeb.WebServices.ReadAllActResponseBody Body;
        
        public ReadAllActResponse() {
        }
        
        public ReadAllActResponse(OnBreakWeb.WebServices.ReadAllActResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReadAllActResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public OnBreakWeb.WebServices.ActividadEmpresa[] ReadAllActResult;
        
        public ReadAllActResponseBody() {
        }
        
        public ReadAllActResponseBody(OnBreakWeb.WebServices.ActividadEmpresa[] ReadAllActResult) {
            this.ReadAllActResult = ReadAllActResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReadAllTipoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadAllTipo", Namespace="http://tempuri.org/", Order=0)]
        public OnBreakWeb.WebServices.ReadAllTipoRequestBody Body;
        
        public ReadAllTipoRequest() {
        }
        
        public ReadAllTipoRequest(OnBreakWeb.WebServices.ReadAllTipoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ReadAllTipoRequestBody {
        
        public ReadAllTipoRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReadAllTipoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadAllTipoResponse", Namespace="http://tempuri.org/", Order=0)]
        public OnBreakWeb.WebServices.ReadAllTipoResponseBody Body;
        
        public ReadAllTipoResponse() {
        }
        
        public ReadAllTipoResponse(OnBreakWeb.WebServices.ReadAllTipoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReadAllTipoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public OnBreakWeb.WebServices.TipoEmpresa[] ReadAllTipoResult;
        
        public ReadAllTipoResponseBody() {
        }
        
        public ReadAllTipoResponseBody(OnBreakWeb.WebServices.TipoEmpresa[] ReadAllTipoResult) {
            this.ReadAllTipoResult = ReadAllTipoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OBServiciosSoapChannel : OnBreakWeb.WebServices.OBServiciosSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OBServiciosSoapClient : System.ServiceModel.ClientBase<OnBreakWeb.WebServices.OBServiciosSoap>, OnBreakWeb.WebServices.OBServiciosSoap {
        
        public OBServiciosSoapClient() {
        }
        
        public OBServiciosSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OBServiciosSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OBServiciosSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OBServiciosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OnBreakWeb.WebServices.HelloWorldResponse OnBreakWeb.WebServices.OBServiciosSoap.HelloWorld(OnBreakWeb.WebServices.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            OnBreakWeb.WebServices.HelloWorldRequest inValue = new OnBreakWeb.WebServices.HelloWorldRequest();
            inValue.Body = new OnBreakWeb.WebServices.HelloWorldRequestBody();
            OnBreakWeb.WebServices.HelloWorldResponse retVal = ((OnBreakWeb.WebServices.OBServiciosSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OnBreakWeb.WebServices.HelloWorldResponse> OnBreakWeb.WebServices.OBServiciosSoap.HelloWorldAsync(OnBreakWeb.WebServices.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<OnBreakWeb.WebServices.HelloWorldResponse> HelloWorldAsync() {
            OnBreakWeb.WebServices.HelloWorldRequest inValue = new OnBreakWeb.WebServices.HelloWorldRequest();
            inValue.Body = new OnBreakWeb.WebServices.HelloWorldRequestBody();
            return ((OnBreakWeb.WebServices.OBServiciosSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OnBreakWeb.WebServices.ReadAllClientesResponse OnBreakWeb.WebServices.OBServiciosSoap.ReadAllClientes(OnBreakWeb.WebServices.ReadAllClientesRequest request) {
            return base.Channel.ReadAllClientes(request);
        }
        
        public OnBreakWeb.WebServices.Cliente[] ReadAllClientes() {
            OnBreakWeb.WebServices.ReadAllClientesRequest inValue = new OnBreakWeb.WebServices.ReadAllClientesRequest();
            inValue.Body = new OnBreakWeb.WebServices.ReadAllClientesRequestBody();
            OnBreakWeb.WebServices.ReadAllClientesResponse retVal = ((OnBreakWeb.WebServices.OBServiciosSoap)(this)).ReadAllClientes(inValue);
            return retVal.Body.ReadAllClientesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OnBreakWeb.WebServices.ReadAllClientesResponse> OnBreakWeb.WebServices.OBServiciosSoap.ReadAllClientesAsync(OnBreakWeb.WebServices.ReadAllClientesRequest request) {
            return base.Channel.ReadAllClientesAsync(request);
        }
        
        public System.Threading.Tasks.Task<OnBreakWeb.WebServices.ReadAllClientesResponse> ReadAllClientesAsync() {
            OnBreakWeb.WebServices.ReadAllClientesRequest inValue = new OnBreakWeb.WebServices.ReadAllClientesRequest();
            inValue.Body = new OnBreakWeb.WebServices.ReadAllClientesRequestBody();
            return ((OnBreakWeb.WebServices.OBServiciosSoap)(this)).ReadAllClientesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OnBreakWeb.WebServices.ReadClienteResponse OnBreakWeb.WebServices.OBServiciosSoap.ReadCliente(OnBreakWeb.WebServices.ReadClienteRequest request) {
            return base.Channel.ReadCliente(request);
        }
        
        public OnBreakWeb.WebServices.Cliente ReadCliente(string rutCliente) {
            OnBreakWeb.WebServices.ReadClienteRequest inValue = new OnBreakWeb.WebServices.ReadClienteRequest();
            inValue.Body = new OnBreakWeb.WebServices.ReadClienteRequestBody();
            inValue.Body.rutCliente = rutCliente;
            OnBreakWeb.WebServices.ReadClienteResponse retVal = ((OnBreakWeb.WebServices.OBServiciosSoap)(this)).ReadCliente(inValue);
            return retVal.Body.ReadClienteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OnBreakWeb.WebServices.ReadClienteResponse> OnBreakWeb.WebServices.OBServiciosSoap.ReadClienteAsync(OnBreakWeb.WebServices.ReadClienteRequest request) {
            return base.Channel.ReadClienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<OnBreakWeb.WebServices.ReadClienteResponse> ReadClienteAsync(string rutCliente) {
            OnBreakWeb.WebServices.ReadClienteRequest inValue = new OnBreakWeb.WebServices.ReadClienteRequest();
            inValue.Body = new OnBreakWeb.WebServices.ReadClienteRequestBody();
            inValue.Body.rutCliente = rutCliente;
            return ((OnBreakWeb.WebServices.OBServiciosSoap)(this)).ReadClienteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OnBreakWeb.WebServices.UpdateClienteResponse OnBreakWeb.WebServices.OBServiciosSoap.UpdateCliente(OnBreakWeb.WebServices.UpdateClienteRequest request) {
            return base.Channel.UpdateCliente(request);
        }
        
        public bool UpdateCliente(OnBreakWeb.WebServices.Cliente cliente) {
            OnBreakWeb.WebServices.UpdateClienteRequest inValue = new OnBreakWeb.WebServices.UpdateClienteRequest();
            inValue.Body = new OnBreakWeb.WebServices.UpdateClienteRequestBody();
            inValue.Body.cliente = cliente;
            OnBreakWeb.WebServices.UpdateClienteResponse retVal = ((OnBreakWeb.WebServices.OBServiciosSoap)(this)).UpdateCliente(inValue);
            return retVal.Body.UpdateClienteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OnBreakWeb.WebServices.UpdateClienteResponse> OnBreakWeb.WebServices.OBServiciosSoap.UpdateClienteAsync(OnBreakWeb.WebServices.UpdateClienteRequest request) {
            return base.Channel.UpdateClienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<OnBreakWeb.WebServices.UpdateClienteResponse> UpdateClienteAsync(OnBreakWeb.WebServices.Cliente cliente) {
            OnBreakWeb.WebServices.UpdateClienteRequest inValue = new OnBreakWeb.WebServices.UpdateClienteRequest();
            inValue.Body = new OnBreakWeb.WebServices.UpdateClienteRequestBody();
            inValue.Body.cliente = cliente;
            return ((OnBreakWeb.WebServices.OBServiciosSoap)(this)).UpdateClienteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OnBreakWeb.WebServices.DeleteClienteResponse OnBreakWeb.WebServices.OBServiciosSoap.DeleteCliente(OnBreakWeb.WebServices.DeleteClienteRequest request) {
            return base.Channel.DeleteCliente(request);
        }
        
        public bool DeleteCliente(string rutCliente) {
            OnBreakWeb.WebServices.DeleteClienteRequest inValue = new OnBreakWeb.WebServices.DeleteClienteRequest();
            inValue.Body = new OnBreakWeb.WebServices.DeleteClienteRequestBody();
            inValue.Body.rutCliente = rutCliente;
            OnBreakWeb.WebServices.DeleteClienteResponse retVal = ((OnBreakWeb.WebServices.OBServiciosSoap)(this)).DeleteCliente(inValue);
            return retVal.Body.DeleteClienteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OnBreakWeb.WebServices.DeleteClienteResponse> OnBreakWeb.WebServices.OBServiciosSoap.DeleteClienteAsync(OnBreakWeb.WebServices.DeleteClienteRequest request) {
            return base.Channel.DeleteClienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<OnBreakWeb.WebServices.DeleteClienteResponse> DeleteClienteAsync(string rutCliente) {
            OnBreakWeb.WebServices.DeleteClienteRequest inValue = new OnBreakWeb.WebServices.DeleteClienteRequest();
            inValue.Body = new OnBreakWeb.WebServices.DeleteClienteRequestBody();
            inValue.Body.rutCliente = rutCliente;
            return ((OnBreakWeb.WebServices.OBServiciosSoap)(this)).DeleteClienteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OnBreakWeb.WebServices.ReadAllActResponse OnBreakWeb.WebServices.OBServiciosSoap.ReadAllAct(OnBreakWeb.WebServices.ReadAllActRequest request) {
            return base.Channel.ReadAllAct(request);
        }
        
        public OnBreakWeb.WebServices.ActividadEmpresa[] ReadAllAct() {
            OnBreakWeb.WebServices.ReadAllActRequest inValue = new OnBreakWeb.WebServices.ReadAllActRequest();
            inValue.Body = new OnBreakWeb.WebServices.ReadAllActRequestBody();
            OnBreakWeb.WebServices.ReadAllActResponse retVal = ((OnBreakWeb.WebServices.OBServiciosSoap)(this)).ReadAllAct(inValue);
            return retVal.Body.ReadAllActResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OnBreakWeb.WebServices.ReadAllActResponse> OnBreakWeb.WebServices.OBServiciosSoap.ReadAllActAsync(OnBreakWeb.WebServices.ReadAllActRequest request) {
            return base.Channel.ReadAllActAsync(request);
        }
        
        public System.Threading.Tasks.Task<OnBreakWeb.WebServices.ReadAllActResponse> ReadAllActAsync() {
            OnBreakWeb.WebServices.ReadAllActRequest inValue = new OnBreakWeb.WebServices.ReadAllActRequest();
            inValue.Body = new OnBreakWeb.WebServices.ReadAllActRequestBody();
            return ((OnBreakWeb.WebServices.OBServiciosSoap)(this)).ReadAllActAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OnBreakWeb.WebServices.ReadAllTipoResponse OnBreakWeb.WebServices.OBServiciosSoap.ReadAllTipo(OnBreakWeb.WebServices.ReadAllTipoRequest request) {
            return base.Channel.ReadAllTipo(request);
        }
        
        public OnBreakWeb.WebServices.TipoEmpresa[] ReadAllTipo() {
            OnBreakWeb.WebServices.ReadAllTipoRequest inValue = new OnBreakWeb.WebServices.ReadAllTipoRequest();
            inValue.Body = new OnBreakWeb.WebServices.ReadAllTipoRequestBody();
            OnBreakWeb.WebServices.ReadAllTipoResponse retVal = ((OnBreakWeb.WebServices.OBServiciosSoap)(this)).ReadAllTipo(inValue);
            return retVal.Body.ReadAllTipoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OnBreakWeb.WebServices.ReadAllTipoResponse> OnBreakWeb.WebServices.OBServiciosSoap.ReadAllTipoAsync(OnBreakWeb.WebServices.ReadAllTipoRequest request) {
            return base.Channel.ReadAllTipoAsync(request);
        }
        
        public System.Threading.Tasks.Task<OnBreakWeb.WebServices.ReadAllTipoResponse> ReadAllTipoAsync() {
            OnBreakWeb.WebServices.ReadAllTipoRequest inValue = new OnBreakWeb.WebServices.ReadAllTipoRequest();
            inValue.Body = new OnBreakWeb.WebServices.ReadAllTipoRequestBody();
            return ((OnBreakWeb.WebServices.OBServiciosSoap)(this)).ReadAllTipoAsync(inValue);
        }
    }
}
